### ISSUE TITLE
Fallback to lower bitrate - TypeError

### ISSUE THREAD

**Issue by alexanderek** [m8tec/Deezync#2]
When trying to load playlist, an error occurs
in logs: TypeError: replace() argument 2 must be str, not None

```
`[INFO] 14:02:52: Syncing 1/1 Deezer playlist 'Rock Essentials' to Plex...
[INFO] 14:02:54: Synced 'Rock Essentials' playlist. Added: 92, removed: 0, missing: 8
[INFO] 14:02:54: Synced Deezer playlists to Plex
[INFO] 14:02:54: Downloading missing tracks
[INFO] 14:02:54: Download Seven Nation Army by The White Stripes...
[INFO] 14:02:55: [The White Stripes - Seven Nation Army] Fallback to lower bitrate
[ERROR] 14:02:55: The White Stripes - Seven Nation Army replace() argument 2 must be str, not None
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deemix/downloader.py", line 468, in downloadWrapper
    result = self.download(extraData, track)
  File "/usr/local/lib/python3.9/site-packages/deemix/downloader.py", line 315, in download
    (filename, filepath, artistPath, coverPath, extrasPath) = generatePath(track, self.downloadObject, self.settings)
  File "/usr/local/lib/python3.9/site-packages/deemix/utils/pathtemplates.py", line 79, in generatePath
    filename = generateTrackName(filenameTemplate, track, settings)
  File "/usr/local/lib/python3.9/site-packages/deemix/utils/pathtemplates.py", line 158, in generateTrackName
    filename = filename.replace("%upc%", track.album.barcode)
TypeError: replace() argument 2 must be str, not None
[INFO] 14:02:55: Downloaded Seven Nation Army by The White Stripes
[INFO] 14:02:55: Download Sweet Child O' Mine by Guns N' Roses...
[INFO] 14:02:56: [Guns N' Roses - Sweet Child O' Mine] Fallback to lower bitrate
[ERROR] 14:02:56: Guns N' Roses - Sweet Child O' Mine replace() argument 2 must be str, not None
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deemix/downloader.py", line 468, in downloadWrapper
    result = self.download(extraData, track)
  File "/usr/local/lib/python3.9/site-packages/deemix/downloader.py", line 315, in download
    (filename, filepath, artistPath, coverPath, extrasPath) = generatePath(track, self.downloadObject, self.settings)
  File "/usr/local/lib/python3.9/site-packages/deemix/utils/pathtemplates.py", line 79, in generatePath
    filename = generateTrackName(filenameTemplate, track, settings)
  File "/usr/local/lib/python3.9/site-packages/deemix/utils/pathtemplates.py", line 158, in generateTrackName
    filename = filename.replace("%upc%", track.album.barcode)
TypeError: replace() argument 2 must be str, not None
[INFO] 14:02:56: Downloaded Sweet Child O' Mine by Guns N' Roses
[INFO] 14:02:56: Download Enter Sandman (Remastered 2021) by Metallica...
[INFO] 14:02:57: Downloaded Enter Sandman (Remastered 2021) by Metallica
[INFO] 14:02:57: Download Dream On by Aerosmith...
[INFO] 14:02:58: [Aerosmith - Dream On] Fallback to lower bitrate
[ERROR] 14:02:58: Aerosmith - Dream On replace() argument 2 must be str, not None
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deemix/downloader.py", line 468, in downloadWrapper
    result = self.download(extraData, track)
  File "/usr/local/lib/python3.9/site-packages/deemix/downloader.py", line 315, in download
    (filename, filepath, artistPath, coverPath, extrasPath) = generatePath(track, self.downloadObject, self.settings)
  File "/usr/local/lib/python3.9/site-packages/deemix/utils/pathtemplates.py", line 79, in generatePath
    filename = generateTrackName(filenameTemplate, track, settings)
  File "/usr/local/lib/python3.9/site-packages/deemix/utils/pathtemplates.py", line 158, in generateTrackName
    filename = filename.replace("%upc%", track.album.barcode)
TypeError: replace() argument 2 must be str, not None`
```

**Comment by m8tec** [comment]
The latest commit should fix this upstream issue.

**Comment by alexanderek** [comment]
thanks
