### ISSUE TITLE
KeyError: 'explicit_lyrics'

### ISSUE THREAD

**Issue by alexanderek** [m8tec/Deezync#3]
crashes when trying to load a track:

```
Traceback (most recent call last):
  File "/app/./main.py", line 357, in <module>
    loop()
  File "/app/./main.py", line 289, in loop
    download_deezer_playlists(deezer_playlist_missing_tracks)
  File "/app/./main.py", line 241, in download_deezer_playlists
    download([track['link']], playlist_config['bitrate'])
  File "/app/./main.py", line 214, in download
    downloadObject = generateDownloadObject(dz, link, bitrate)
  File "/usr/local/lib/python3.9/site-packages/deemix/__init__.py", line 64, in generateDownloadObject
    return generateTrackItem(dz, link_id, bitrate)
  File "/usr/local/lib/python3.9/site-packages/deemix/itemgen.py", line 48, in generateTrackItem
    'explicit': trackAPI['explicit_lyrics'],
KeyError: 'explicit_lyrics'
```

**Comment by m8tec** [comment]
Could you please give an example for a track you are trying to load which causes this error?

**Comment by alexanderek** [comment]
I can no longer reproduce this error, possibly because the content of the playlist might have changed. I think we can close the issue.

**Comment by m8tec** [comment]
Ok, closed until we stumble upon it again
